[package]
name = "department"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5.30", features = ["derive"] }
csv = "1.1"
serde = {version = "1", features = ["derive"]}
